# Configurações sensíveis (não versionar)
GOOGLE_CLIENT_ID = "209223702106-ct75alsn39bdr5n3i7mq844uveioi5d3.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"

[database]
path = "data/bjj_digital.db"
